version: '3.8'

services:
  apitalk:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apitalk
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_MODEL=${OPENAI_MODEL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - apitalk_network

networks:
  apitalk_network:
    driver: bridge
